<?php
$apparelHelper = $this->helper('Hidden\Apparel\Helper\Data');
$enablePromotion = $apparelHelper->getConfigValue('apparelsettings/promotion_settings/enable_promotion');
$promotionText = $apparelHelper->getConfigValue('apparelsettings/promotion_settings/promotion_text');
?>
<?php if ($enablePromotion == 1) { ?>
    <?php if ($promotionText != '') { ?>
        <div class="promotion-wrapper">
            <div class="page-main">
                <?php echo $promotionText; ?>
            </div>
        </div>
    <?php } ?>
<?php } ?>